// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/channel/:id": {
    params: {
      "id": string;
    };
  };
  "/video/:id": {
    params: {
      "id": string;
    };
  };
  "/search": {
    params: {};
  };
  "/search/watch/:videoId": {
    params: {
      "videoId": string;
    };
  };
  "/search/:searchTerm": {
    params: {
      "searchTerm": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/channel/:id" | "/video/:id" | "/search" | "/search/watch/:videoId" | "/search/:searchTerm";
  };
  "routes/channel.$id.tsx": {
    id: "routes/channel.$id";
    page: "/channel/:id";
  };
  "routes/video.$id.tsx": {
    id: "routes/video.$id";
    page: "/video/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search" | "/search/watch/:videoId" | "/search/:searchTerm";
  };
  "routes/search.watch.$videoId.tsx": {
    id: "routes/search.watch.$videoId";
    page: "/search/watch/:videoId";
  };
  "routes/search.$searchTerm.tsx": {
    id: "routes/search.$searchTerm";
    page: "/search/:searchTerm";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/channel.$id": typeof import("./src/routes/channel.$id.tsx");
  "routes/video.$id": typeof import("./src/routes/video.$id.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/search": typeof import("./src/routes/search.tsx");
  "routes/search.watch.$videoId": typeof import("./src/routes/search.watch.$videoId.tsx");
  "routes/search.$searchTerm": typeof import("./src/routes/search.$searchTerm.tsx");
};